spring.application.name=products-service

server.port=8989

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerse
spring.datasource.username=root
spring.datasource.password=qwerty

# Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialect (optional in newer versions)
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Admin Server Client
spring.boot.admin.client.url=http://localhost:1111


# Config Server
spring.config.import=optional:configserver:http://localhost:2222
